### PR TITLE
Add OpenGraph HTML metadata in the test report.

### PR DESCRIPTION
**Pull request by hubjac1**
Hello,
This PR to add openGraph HTML metadata. So that the test report can be preview when shared on chat or social network.
capture d ecran 2019-03-07 a 19 52 10

### CODE REVIEW

**Comment by wswebcreation** [comment]
Hi @hubjac1 

Tnx for the PR. I'll try to look at it the coming days. Will let you know

**Comment by hubjac1** [comment]
Hi,
I try to make it better with this.


### `ogServerUrl`
- **Type:** `string`
- **Mandatory:** No

Url used in the open graph HTML metadata of the test report. 

[OpenGraph protocol](http://ogp.me/) enable smart preview of test report on chat or social network.
This URL has to be the public URL of the test report's directory. Then you can post your ogServerUrl/index.html on your favorite chat room to share the report with a smart preview.

**Comment by wswebcreation** [comment]
@hubjac1 

I'm so sorry that I didn't look at this PR, I also got a bot that closed it and it didn't trigger me . to watch it again.

I re-opened it again, can you take a look at the merge conflict and describe a little bit how people can use it in their chat app? Like which url needs to be loaded, with which chat's does it work and so on?

Tnx

**Comment by wswebcreation** [comment]
Closing it now

**Pull request closed without merging**
