### PR TITLE
feat(report-generator): be able to provide a custom template for features overview

### PR DESCRIPTION
**Pull request by hdorgeval**
The purpose of this PR is to be able to provide a custom template of `features-overview.tmpl` or `features-overview-custom-metadata` (if using custom metadata).

For this purpose, a new option `customTemplate` can be provided to the `generate` method:

```js
const report = require('multiple-cucumber-html-reporter');
report.generate({
  saveCollectedJSON: true,
  jsonDir: './test/unit/data/json/',
  reportPath: './.tmp/browsers/custom-templates/',
  reportName: 'You can adjust this report name',
  customMetadata: false,
  displayDuration: true,
  durationInMS: true,
  customTemplate: {
	featuresOverview: path.join(__dirname, 'custom-templates', 'features-overview.tmpl')
  }
});
```

PS: I am using vscode together with prettier. I had a lot of trouble to have a minimal impact in the existing code base. This is why I created a vscode settings file to ensure changes in code styling is minimal. If you think too much modifications have been done, feel free to ask for a revert.

Regards
Henri d'Orgeval

### CODE REVIEW

**Comment by wswebcreation** [comment]
Hi @hdorgeval 

Thanks for the PR and no problem that you needed to adjust a lot of code. I still want to refactor this module into a better structured module but why fix if it ain't broken 😉 .

I was wondering what the use case is for this PR, is it to hide certain columns? If so then it might be better to adjust that instead of providing a complete new template file. I'm planning to remove Lodash in the future which will certainly be breaking your feature.

Please let me know what you think.

**Comment by hdorgeval** [comment]
Hi @wswebcreation , the use case for this PR is to be able to add a column inside the 'standard' features overview and to slightly modify rendering of the first column) (see the snapshot I have added in the images folder: you will see I have customised the first column and added a new one). 

This new column should show the execution date of the feature.

I have developed a reporter for `TestCafé` that emits json files with the same structure as the ones generated by cucumber: 
[testcafe-reporter-cucumber-json](https://github.com/hdorgeval/testcafe-reporter-cucumber-json)

I would like to show some data specific to TestCafé, without using custom metadata. One of this specific data is the execution date/time of the feature.

Another way of solving this problem, could be to add in the features overview template a new column that shows the creation date/time of the json file and conditionally show this new column with an option like `showDate: true|false`.

I thought it could be more versatile to be able to completely override the template file with a custom one. 
I understand that such a feature could be broken when you remove lodash, but I am sure you will still use a templating mechanism to generate the HTML report.

I was even wondering that being able to override any of your internal templates (with the mechanism based on this PR) could be a nice way for anyone to test in advance and propose a new design or a new version of an existing template, so that it might save you a lot of time. You could even share on your repo all these alternative templates provided by the community!

Feel free to discard this PR, if you think my use case is too specific or if it will introduce too much overhead in the future.

**Comment by wswebcreation** [comment]
Hi @hdorgeval 

I like your thoughts, but to support that I really want to implement the new parser first. Can you change this PR to only enable/disable the column you need?

**Comment by hdorgeval** [comment]
Hi @wswebcreation , thank you for your response. 

I will go your way and create another PR this week-end.

Thanks!

**Pull request closed without merging**
