### PR TITLE
fix: file name formatting by xregexp

### PR DESCRIPTION
**Pull request by Seunghyum**
Hello :)
I still use your wonderful library. Thanks a lot.

This pr is from https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/148

I'm sorry about my inactivity.

Now I see your answer. thank you
I made another solution to cover all language. 
[xregexp](https://www.npmjs.com/package/xregexp) package is little bit big (154.4 kb, gzipped 51.4kb).
But it will be worth to take :)

If you want to make test case, I will make it in this pr. ;)
Thanks to read my pr

### CODE REVIEW

**Comment by Seunghyum** [comment]
Oh, I see your solution https://github.com/wswebcreation/multiple-cucumber-html-reporter/pull/148#discussion_r689451200
```
feature.id = `${ idPrefix }${ feature.id }`.split(" ").join("-").replace(/[^a-zA-Z0-9-_]/g, '-');
```
Your sugestion is also good. if you want to change your code, i will pr it :)

**Comment by wswebcreation** [comment]
Hi @Seunghyum 

Feel free to fix it, then it will be on your name

**Comment by Seunghyum** [comment]
> Hi @Seunghyum
> 
> Feel free to fix it, then it will be on your name

Okey I will pr soon :) thanks alot

**Comment by BaCaRoZzo** [comment]
@Seunghyum I'll close this PR then, feel free to submit the new one at your earliest convenience. Thanks a lot for your engagement! 😊

**Pull request closed without merging**
