### PR TITLE
Remove base64 encoding for text/plain mimetype

### LINKED ISSUE #46: Invalid characters being reported
I see the following in the report:

[
  **"��^�,e",**
  [
    {
      "key": val
    }
  ]
]

This happens for the following cucumber JSON results:
"embeddings": [
              {
                "data": **"orderCxl"**,
                "mime_type": "text/plain"
              },
              {
                "data": "[{\"key\":val}]",
                "mime_type": "application/json"
              }
            ]

It only happens when the data is orderCxl.  For any other value for the first data, it reports correctly.

### PR DESCRIPTION
**Pull request by BaCaRoZzo**
Fixes #46 

The actual fix is in https://github.com/wswebcreation/multiple-cucumber-html-reporter/commit/66de54994abcf59e4f86fcf23ff6eb9632cacb95, the rest are just improvements and minor fixes which, I hope, are welcome as well. :slightly_smiling_face: 

Regarding the fix itself, it simply removes the encoding for `text/plain` but also reworks a bit the template. Basically `step.text` and `step.json` were overlapping causing the two to end up in the same `div`. I don't think that was wanted as we have two separated `div`s for `json` and `text`. Hence, I've made sure to correctly split them.

`orderCxl` has been added to the tests and it is indeed processed as expected now.

### CODE REVIEW

**Comment by BaCaRoZzo** [comment]
@wswebcreation I think we should apply the same treatment to `text/html`, i.e. remove the `base64` encoding also there. Since I'm not sure what's the feeling about that I left that for the PR discussion. :smile:

**Review by wswebcreation — APPROVED** [review]
Wow @BaCaRoZzo 

Thanks for all the fixes!

Regarding this

> @wswebcreation I think we should apply the same treatment to text/html, i.e. remove the base64 encoding also there. Since I'm not sure what's the feeling about that I left that for the PR discussion. 😄

Yes, please, can you also fix it there?

**Comment by BaCaRoZzo** [comment]
@wswebcreation done as requested. Also dropped the library in a separate commit since it went unused.

**Comment by wswebcreation** [comment]
Thanks @BaCaRoZzo !

**Pull request merged**
