### PR TITLE
* Added Headless icon and Filter logic based on scenarios result. 

### PR DESCRIPTION
**Pull request by bhaslamb**
@wswebcreation  - 
* With current version headless icon is missing in font awesome hence added it as svg icon so please check my PR here.
* Added drop down options to filter scenarios based on test results, attached sample image here.
It would be really helpful if you can review and release it.

Headless Icon
image

Filter Logic Screenshot
image

### CODE REVIEW

**Review by wswebcreation — CHANGES_REQUESTED** [review]
Wow @bhaslamb 
Thanks for this!! You're really doing great things here. 

Can you take a look at the failing tests, if that's fixed I can release a new version

**Comment by bhaslamb** [comment]
@wswebcreation - unit test fixed. please check and let me know if there is any issues.

**Comment by bhaslamb** [comment]
Wow. will fix this failure now.

**Comment by bhaslamb** [comment]
@wswebcreation  - All tests passed. please let me know if you are see anything.

**Comment by wswebcreation** [comment]
Thanks man!!!

**Comment by sseenivasan89** [comment]
Hi Team,

looks like the filter is not working with 3.5.0

**Pull request merged**
